#!/usr/bin/env python3

import sys
import os
sys.path.append('/Users/anishlaha/Documents/GitHub/BraillifyAI')

from app.services import TextOptimizationService

def debug_optimization():
    """Debug text optimization with sample poor text"""
    
    # This is similar to what the user is seeing - a poorly extracted PDF with artifacts
    sample_poor_text = """
Physics Internal Assessment Investigating the Effect of Blade Pitch Angle on the Thrust
Generated by a Propeller How does varying the blade pitch angle from 0° to 180° in 15°
increments affect the thrust generated by a 3-blade propeller at a constant rotational speed?
Word count: 1753 Candidate ID: Table of Contents 1. Introduction 1. Introduction 
.............................................................................................. 4 A. research question
.............................................................................................. 4 2. Theoretical Framework
theoretical framework .................................................................................... 4 A. blade
pitch angle .................................................................................................. 4 B. lift and
thrust force ................................................................................................ 5 C. blade element
theory (bet) ............................................................................................... 6 3. Experimental Design
3. experimental design ......................................................................................
hypothesis .................................................................................................. 7
variables .................................................................................................... 7
independent variable: ....................................................................................... 7 2.
dependent variable: ......................................................................................... 7 3. controlled
variables: .................................................................................................. 7 C. apparatus
..................................................................................................... 8 D. methodology
..................................................................................................... 8 1. apparatus setup
..................................................................................................... 8 2. procedure
..................................................................................................... 8
"""
    
    print("🔤 ORIGINAL POORLY EXTRACTED TEXT:")
    print("-" * 80)
    print(sample_poor_text[:500] + "...")
    print()
    
    # Test the optimization
    print("🤖 TESTING OPTIMIZATION...")
    optimization_service = TextOptimizationService()
    result = optimization_service.optimize_extracted_text(sample_poor_text, "physics")
    
    if result.get('optimized_text'):
        print("✅ OPTIMIZED TEXT:")
        print("-" * 80)
        print(result['optimized_text'])
        print()
        print("📊 STATS:")
        print(f"- Original length: {result['original_length']} chars")
        print(f"- Optimized length: {result['optimized_length']} chars")
        print(f"- Model used: {result['model_used']}")
        print(f"- Improvements: {result['improvement_notes']}")
    else:
        print("❌ OPTIMIZATION FAILED")
        print("Error or no result returned")

if __name__ == "__main__":
    debug_optimization()
