services:
  # Single web service (free tier compatible)
  - type: web
    name: braillifyai
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB
      - key: BRAILLE_API_URL
        value: http://localhost:10001
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
