"""Add braille and optimization columns

Revision ID: 8ed04d4cc3d5
Revises: 231a3b3ea0b2
Create Date: 2025-06-23 10:29:49.298742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed04d4cc3d5'
down_revision = '231a3b3ea0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimized_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('optimization_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_optimized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('optimization_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ocr_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ocr_word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_ocr_processed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ocr_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('braille_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('braille_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('braille_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('braille_chars_per_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('braille_lines_per_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_braille_converted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('braille_conversion_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processing_steps', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('processing_steps')
        batch_op.drop_column('braille_conversion_date')
        batch_op.drop_column('is_braille_converted')
        batch_op.drop_column('braille_lines_per_page')
        batch_op.drop_column('braille_chars_per_page')
        batch_op.drop_column('braille_pages')
        batch_op.drop_column('braille_grade')
        batch_op.drop_column('braille_text')
        batch_op.drop_column('ocr_date')
        batch_op.drop_column('is_ocr_processed')
        batch_op.drop_column('ocr_word_count')
        batch_op.drop_column('ocr_confidence')
        batch_op.drop_column('ocr_text')
        batch_op.drop_column('optimization_date')
        batch_op.drop_column('is_optimized')
        batch_op.drop_column('optimization_notes')
        batch_op.drop_column('optimized_text')

    # ### end Alembic commands ###
